import { Ollama } from 'ollama';
import { CONFIG } from '../config';
import { ResearchState } from '../state';
import { extractJsonFromReasoning } from '../utils/think-interceptor';
import { PlannerOutputSchema } from '../schemas';

const ollama = new Ollama({ host: CONFIG.OLLAMA_BASE_URL });

export async function runPlannerNode(state: ResearchState): Promise<ResearchState> {
  console.log('🧠 Strategy Planner: Formulating research plan and search queries...');
  const prompt = `You are an expert geopolitical and financial research director.
Your objective is to generate a research plan and search queries to build a comprehensive GeoIntelligence dossier.

Target Company: ${state.companyName} (${state.ticker})
User Query: ${state.userQuery}

Constraint 1 (Reasoning Channel): You must output your internal evaluation using the designated reasoning tags prior to your final decision. You must use <think> and </think> tags.
Constraint 2 (Query Design): Generate 3 to 5 highly specific search strings to query the internet. These queries should aim to uncover: offices/facilities with coordinates, revenue geography, supply chain, customers, geopolitical risks, and expansion/contraction signals.
Constraint 3 (JSON Output): After your reasoning, output valid JSON matching exactly this shape:
{
  "researchPlan": "A string detailing the strategic methodology generated by the LLM.",
  "searchQueries": ["query 1", "query 2", "query 3"]
}

Now begin your analysis.`;

  const response = await ollama.chat({
    model: CONFIG.REASONING_MODEL,
    messages: [{ role: 'user', content: prompt }],
    options: {
      temperature: 0.1,
    }
  });

  const rawContent = response.message.content;
  const jsonString = extractJsonFromReasoning(rawContent);

  try {
    const rawData = JSON.parse(jsonString);
    const parsed = PlannerOutputSchema.parse(rawData);

    state.researchPlan = parsed.researchPlan;
    state.searchQueries = parsed.searchQueries;

    console.log(`✅ Strategy Planner generated ${parsed.searchQueries.length} search queries.`);
    parsed.searchQueries.forEach((q, i) => console.log(`   ${i + 1}. ${q}`));
    
    return state;
  } catch (error) {
    console.error('❌ Planner failed to generate valid JSON:', error);
    console.log('Raw content to parse:', jsonString);
    throw error;
  }
}
